package task

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"slices"
	"sync"
	"time"

	"golang.org/x/sync/errgroup"
)

// File is the taskfile schema. JSON rather than TOML because a taskfile is
// generated by other programs most of the time, and stdlib JSON needs no new
// dependency to parse it.
type File struct {
	Name     string            `json:"name"`
	Defaults Defaults          `json:"defaults"`
	Tasks    []json.RawMessage `json:"tasks"`

	// Parsed holds the tasks after UnmarshalFile, which is a two-step decode
	// because defaults only apply once every task has been read.
	Parsed []Task `json:"-"`
}

// Defaults are the values a task inherits. Instance is required somewhere: a
// task that names no instance and inherits none has nothing to run against.
type Defaults struct {
	Instance    string            `json:"instance"`
	Model       string            `json:"model"`
	Provider    string            `json:"provider"`
	Thinking    string            `json:"thinking"`
	Timeout     Duration          `json:"timeout"`
	Parallel    int               `json:"parallel"`
	AutoApprove *bool             `json:"auto_approve"`
	Extra       map[string]string `json:"extra"`
}

// Task is one prompt. Every field is optional and falls back to Defaults.
type Task struct {
	ID          string   `json:"id"`
	Instance    string   `json:"instance"`
	Prompt      string   `json:"prompt"`
	Prompts     []string `json:"prompts"`
	Model       string   `json:"model"`
	Provider    string   `json:"provider"`
	Thinking    string   `json:"thinking"`
	Session     string   `json:"session"`
	Continue    bool     `json:"continue"`
	Title       string   `json:"title"`
	Files       []string `json:"files"`
	Timeout     Duration `json:"timeout"`
	AutoApprove *bool    `json:"auto_approve"`
	Extra       []string `json:"extra"`

	// index is position in the file, used for the default id.
	index int
}

// Duration accepts either a Go duration string ("90s", "2m") or a bare number
// of seconds, because a generated taskfile often has the latter and a hand
// written one has the former.
type Duration time.Duration

func (d *Duration) UnmarshalJSON(b []byte) error {
	var num json.Number
	if err := json.Unmarshal(b, &num); err == nil {
		if f, err := num.Float64(); err == nil {
			*d = Duration(time.Duration(f * float64(time.Second)))
			return nil
		}
	}
	var s string
	if err := json.Unmarshal(b, &s); err != nil {
		return fmt.Errorf("timeout must be a duration string or seconds: %w", err)
	}
	if s == "" {
		*d = 0
		return nil
	}
	tm, err := time.ParseDuration(s)
	if err != nil {
		return fmt.Errorf("timeout %q: %w", s, err)
	}
	*d = Duration(tm)
	return nil
}

func (d Duration) Go() time.Duration { return time.Duration(d) }

// Request is one unit of work handed to a Runner. The task package does not
// know about instances, drivers or environments; the caller does, and this is
// the whole seam between them.
type Request struct {
	Task        Task
	Index       int
	Total       int
	Model       string
	Provider    string
	Thinking    string
	Timeout     time.Duration
	AutoApprove bool
}

// Outcome is what one task produced.
type Outcome struct {
	Task        Task
	Instance    string
	Answer      string
	Events      []json.RawMessage
	Err         error
	ExitCode    int
	TimedOut    bool
	Log         string
	SessionID   string
	Duration    time.Duration
	Usage       map[string]float64
	RingDropped int
}

// Runner executes a single request. Implemented by package cli; kept as an
// interface so this package can be tested with a fake that sleeps, fails, or
// emits events.
type Runner func(ctx context.Context, req Request) Outcome

// Options controls the fan-out.
type Options struct {
	Parallel int
	MaxRing  int
	// OnStart fires before a task begins, so a progress line appears even for
	// tasks that never produce output.
	OnStart func(req Request)
	// OnDone fires as each task finishes, in completion order.
	OnDone func(out Outcome, done, total int)
}

// Ring keeps the last N events without holding a whole transcript in memory. A
// long agent run can emit hundreds of thousands of events; the summary only
// needs the tail, and the full NDJSON is on disk regardless.
type Ring struct {
	mu      sync.Mutex
	size    int
	items   []json.RawMessage
	dropped int
}

func NewRing(size int) *Ring {
	if size <= 0 {
		size = 200
	}
	return &Ring{size: size}
}

func (r *Ring) Add(b json.RawMessage) {
	r.mu.Lock()
	defer r.mu.Unlock()
	if len(r.items) < r.size {
		r.items = append(r.items, b)
		return
	}
	copy(r.items, r.items[1:])
	r.items[len(r.items)-1] = b
	r.dropped++
}

func (r *Ring) Slice() ([]json.RawMessage, int) {
	r.mu.Lock()
	defer r.mu.Unlock()
	return append([]json.RawMessage(nil), r.items...), r.dropped
}

// UnmarshalFile reads and validates a taskfile, applying defaults.
func UnmarshalFile(path string) (*File, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var f File
	if err := json.Unmarshal(data, &f); err != nil {
		return nil, fmt.Errorf("parse %s: %w", path, err)
	}
	if len(f.Tasks) == 0 {
		return nil, fmt.Errorf("%s: no tasks", path)
	}
	for i, raw := range f.Tasks {
		var t Task
		if err := json.Unmarshal(raw, &t); err != nil {
			return nil, fmt.Errorf("%s task %d: %w", path, i+1, err)
		}
		t.index = i
		if t.Instance == "" {
			t.Instance = f.Defaults.Instance
		}
		if t.Model == "" {
			t.Model = f.Defaults.Model
		}
		if t.Provider == "" {
			t.Provider = f.Defaults.Provider
		}
		if t.Thinking == "" {
			t.Thinking = f.Defaults.Thinking
		}
		if t.Timeout == 0 {
			t.Timeout = f.Defaults.Timeout
		}
		if t.AutoApprove == nil {
			t.AutoApprove = f.Defaults.AutoApprove
		}
		if t.ID == "" {
			t.ID = fmt.Sprintf("%s-%d", orDefault(t.Instance, "task"), i+1)
		}
		// A task may hold one prompt or a list; the list expands into separate
		// runs so a sweep over N questions is one file rather than N files.
		texts := t.Prompts
		if len(texts) == 0 {
			texts = []string{t.Prompt}
		}
		for j, p := range texts {
			clone := t
			clone.Prompt = p
			clone.Prompts = nil
			if p == "" {
				return nil, fmt.Errorf("%s task %d: prompt is empty", path, i+1)
			}
			if len(texts) > 1 {
				clone.ID = fmt.Sprintf("%s/%d", t.ID, j+1)
			}
			f.Parsed = append(f.Parsed, clone)
		}
	}
	if bad := slices.IndexFunc(f.Parsed, func(t Task) bool { return t.Instance == "" }); bad >= 0 {
		return nil, fmt.Errorf("%s task %d: no instance and no defaults.instance", path, bad+1)
	}
	seen := map[string]int{}
	for _, t := range f.Parsed {
		seen[t.ID]++
	}
	for id, n := range seen {
		if n > 1 {
			return nil, fmt.Errorf("%s: task id %q is used %d times; ids must be unique", path, id, n)
		}
	}
	return &f, nil
}

// Run executes every task with bounded parallelism. A failing task is recorded
// and the rest continue, since one bad prompt in a sweep of fifty is not a
// reason to lose the other forty-nine. A cancellation is different: it means the
// operator stopped us, so remaining tasks are not started.
func Run(ctx context.Context, f *File, run Runner, opt Options) ([]Outcome, error) {
	total := len(f.Parsed)
	limit := opt.Parallel
	if limit <= 0 {
		limit = f.Defaults.Parallel
	}
	if limit <= 0 {
		limit = 2
	}
	if limit > total {
		limit = total
	}

	var (
		mu       sync.Mutex
		outcomes []Outcome
		done     int
	)
	// errgroup with SetLimit: the first error cancels the shared context, which
	// reaches every child's process group through execd.
	g, gctx := errgroup.WithContext(ctx)
	g.SetLimit(limit)

	for i, t := range f.Parsed {
		req := Request{
			Task:  t,
			Index: i,
			Total: total,
			Model: t.Model, Provider: t.Provider, Thinking: t.Thinking,
			Timeout:     t.Timeout.Go(),
			AutoApprove: t.AutoApprove == nil || *t.AutoApprove,
		}
		g.Go(func() error {
			if gctx.Err() != nil {
				return gctx.Err()
			}
			if opt.OnStart != nil {
				opt.OnStart(req)
			}
			out := run(gctx, req)
			if out.Task.ID == "" {
				out.Task = t
			}
			if out.Instance == "" {
				out.Instance = t.Instance
			}
			mu.Lock()
			done++
			outcomes = append(outcomes, out)
			n := done
			mu.Unlock()
			if opt.OnDone != nil {
				opt.OnDone(out, n, total)
			}
			if out.Err != nil {
				// A failed task is reported and the fan-out continues; only a
				// cancellation stops it, because that means the user asked us
				// to stop spending.
				if errors.Is(out.Err, context.Canceled) || errors.Is(out.Err, context.DeadlineExceeded) {
					return out.Err
				}
			}
			return nil
		})
	}
	err := g.Wait()
	slices.SortStableFunc(outcomes, func(a, b Outcome) int { return a.Task.index - b.Task.index })
	return outcomes, err
}

func orDefault(s, def string) string {
	if s == "" {
		return def
	}
	return s
}
