import { useState } from 'react';
import { Folder, FileText, CheckCircle2, ShieldAlert, ShieldCheck, Cpu, Network, Lock, FileCode, ArrowRight } from 'lucide-react';

interface FileNode {
  name: string;
  type: 'folder' | 'file';
  desc: string;
  content?: string;
  highlight?: boolean;
}

const INSTANCE_STRUCTURE: FileNode[] = [
  {
    name: 'bin/',
    type: 'folder',
    desc: 'First entry on the instance PATH. Holds downloaded agent binary or local wrapper scripts.',
    content: `# Contains private agent binary or symlink
# Precedence: This directory is placed first on PATH
# Executables here override ambient host binaries
-rwxr-xr-x 1 user user 42M cline`
  },
  {
    name: 'home/',
    type: 'folder',
    desc: 'Redirected $HOME for the instance. The agent creates its dotfiles and local caches here.',
    content: `# The agent process sees this as /home/user/
# Any files written to ~/.local or ~/.config land in this subtree
drwx------ 3 user user 4096 .cline/
drwx------ 2 user user 4096 .ssh/`
  },
  {
    name: 'config/',
    type: 'folder',
    desc: 'XDG_CONFIG_HOME. Isolated application configuration, MCP connections, and tool parameters.',
    content: `# XDG_CONFIG_HOME redirect
-rw------- 1 user user 2410 cline_mcp_settings.json
-rw-r--r-- 1 user user  512 settings.json`
  },
  {
    name: 'data/',
    type: 'folder',
    desc: 'XDG_DATA_HOME. Dedicated database and conversation history files (e.g., kilo.db, sqlite).',
    content: `# XDG_DATA_HOME redirect
# Stores per-instance conversation history and agent state
-rw------- 1 user user 18M kilo.db`
  },
  {
    name: 'logs/',
    type: 'folder',
    desc: 'Run transcripts (.ndjson), proxy audit reports (.txt), and SHA256 hashes of install scripts.',
    content: `# Audit transcripts and provenance records
-rw-r--r-- 1 user user 4820 run-20261001-1345-01.ndjson
-rw-r--r-- 1 user user 1024 env-20261001-1345-01.txt`
  },
  {
    name: 'launcher',
    type: 'file',
    desc: 'Generated bash executable script rendering the exact environment built by BuildEnv.',
    content: `#!/usr/bin/env bash
# Generated by golunch v1.0.0 — DO NOT EDIT
# Tested for exact parity with golunch run
set -eo pipefail

export HOME="/home/user/.golunch/instances/work/home"
export XDG_CONFIG_HOME="/home/user/.golunch/instances/work/config"
export XDG_DATA_HOME="/home/user/.golunch/instances/work/data"
export XDG_CACHE_HOME="/home/user/.golunch/instances/work/cache"
export XDG_STATE_HOME="/home/user/.golunch/instances/work/state"
export XDG_RUNTIME_DIR="/home/user/.golunch/instances/work/runtime"
export TMPDIR="/home/user/.golunch/instances/work/tmp"
export PATH="/home/user/.golunch/instances/work/bin:$PATH"

# Proxy injection: 8 variables synchronized
unset HTTP_PROXY http_proxy HTTPS_PROXY https_proxy ALL_PROXY all_proxy NO_PROXY no_proxy
export HTTP_PROXY="http://127.0.0.1:7890"
export http_proxy="http://127.0.0.1:7890"
export HTTPS_PROXY="http://127.0.0.1:7890"
export https_proxy="http://127.0.0.1:7890"
export NO_PROXY="localhost,127.0.0.1,127.0.0.0/8,::1,.localhost,169.254.169.254"
export no_proxy="localhost,127.0.0.1,127.0.0.0/8,::1,.localhost,169.254.169.254"

exec /home/user/.golunch/instances/work/bin/cline "$@"`
  },
  {
    name: 'metadata.toml',
    type: 'file',
    desc: 'Per-instance metadata recording the driver agent, assigned proxy profile, and creation settings.',
    content: `[instance]
alias      = "work"
agent      = "cline"
created_at = "2026-10-01T13:45:00Z"
shell      = "/bin/bash"

[proxy]
profile    = "corp"
url        = "http://127.0.0.1:7890"
no_proxy   = [".internal.company.com"]`
  },
  {
    name: '.work.lock',
    type: 'file',
    desc: 'Kernel POSIX advisory flock file. Automatically unlocked by Linux/macOS on process exit.',
    content: `# Advisory flock state:
# - Normal agent runs: LOCK_SH (shared read lock)
# - Admin tasks (install, seed, rm): LOCK_EX (exclusive lock)
# Crash-safe: if the process is killed or crashes, the OS kernel immediately releases the descriptor.`
  }
];

export const ArchitectureSection = () => {
  const [selectedNode, setSelectedNode] = useState<FileNode>(INSTANCE_STRUCTURE[5]); // launcher
  const [activeProxyTier, setActiveProxyTier] = useState<number>(0);

  const proxyTiers = [
    {
      tier: '1. Command Flag',
      spec: '--proxy <url|profile> / --noproxy',
      description: 'Highest precedence. Injected at invocation time; overrides all stored configurations for that specific run.',
      badge: 'Priority 1 (Wins)'
    },
    {
      tier: '2. Instance Config',
      spec: '~/.golunch/instances/<alias>/metadata.toml',
      description: 'Defined per-instance upon creation or via configuration edits. Applies automatically whenever the alias is used.',
      badge: 'Priority 2'
    },
    {
      tier: '3. Global Default',
      spec: '~/.golunch/config.toml (defaults.proxy)',
      description: 'Fallback proxy or named profile for any instance that does not specify an explicit override.',
      badge: 'Priority 3'
    },
    {
      tier: '4. Ambient Host',
      spec: 'Host environment variables ($HTTP_PROXY, etc.)',
      description: 'Used only if no golunch proxy configurations are provided. Note: proxy = "none" force-unsets all 8 variables.',
      badge: 'Priority 4 (Lowest)'
    }
  ];

  return (
    <section id="architecture" className="py-20 border-t border-neutral-800/80 bg-neutral-950">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        
        {/* Section Header */}
        <div className="max-w-3xl mb-16">
          <div className="text-xs font-mono text-amber-400 uppercase tracking-wider mb-2">
            Engine Mechanics
          </div>
          <h2 className="text-3xl sm:text-4xl font-extrabold text-white font-display tracking-tight">
            How isolation works without containers.
          </h2>
          <p className="mt-4 text-neutral-300 text-base leading-relaxed">
            Docker introduces massive overhead and virtualization friction. <code className="text-amber-300 font-mono">golunch</code> achieves real, auditable isolation through POSIX standards: dedicated directory trees, strict environment variable redirection, and kernel-managed advisory locking.
          </p>
        </div>

        {/* Comparison: Containers vs. golunch */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 mb-16">
          {/* Container Approach */}
          <div className="p-6 rounded-xl border border-neutral-800 bg-neutral-900/40 space-y-4">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2.5 text-neutral-300 font-semibold text-base">
                <Cpu className="w-5 h-5 text-neutral-400" />
                <span>The Container Trap (Docker / Podman)</span>
              </div>
              <span className="text-xs font-mono text-neutral-400">Heavyweight</span>
            </div>

            <p className="text-sm text-neutral-400 leading-relaxed">
              Wrapping coding agents inside Docker containers requires running a root-privileged daemon, mounting host source trees through complex volume bindings, paying 500MB+ in memory overhead per container, and dealing with permission mismatch between container and host users.
            </p>

            <div className="space-y-2 pt-2 text-xs font-mono">
              <div className="flex items-start gap-2 text-neutral-400">
                <span className="text-rose-400 shrink-0">✕</span>
                <span>Requires background system daemon running at all times</span>
              </div>
              <div className="flex items-start gap-2 text-neutral-400">
                <span className="text-rose-400 shrink-0">✕</span>
                <span>Cold start startup latency: 1,500ms+ per invocation</span>
              </div>
              <div className="flex items-start gap-2 text-neutral-400">
                <span className="text-rose-400 shrink-0">✕</span>
                <span>UID 0 / root permission leakage and filesystem binding friction</span>
              </div>
              <div className="flex items-start gap-2 text-neutral-400">
                <span className="text-rose-400 shrink-0">✕</span>
                <span>No direct access to host developer tools without rebuilding images</span>
              </div>
            </div>
          </div>

          {/* golunch Approach */}
          <div className="p-6 rounded-xl border border-amber-500/40 bg-amber-500/[0.03] space-y-4">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2.5 text-white font-semibold text-base">
                <ShieldCheck className="w-5 h-5 text-amber-400" />
                <span>The golunch Paradigm: Pure Process Harness</span>
              </div>
              <span className="text-xs font-mono text-amber-400">0ms Overhead</span>
            </div>

            <p className="text-sm text-neutral-300 leading-relaxed">
              An instance is a directory tree plus an environment builder. The agent process is launched natively on the host under your own user account with redirected XDG directories, private HOME, and dedicated proxy headers. Zero daemon, zero virtualization, zero lag.
            </p>

            <div className="space-y-2 pt-2 text-xs font-mono">
              <div className="flex items-start gap-2 text-neutral-200">
                <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0" />
                <span>Runs as normal user (explicitly refuses root uid 0 for safety)</span>
              </div>
              <div className="flex items-start gap-2 text-neutral-200">
                <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0" />
                <span>Zero startup overhead: executes child process immediately (0ms)</span>
              </div>
              <div className="flex items-start gap-2 text-neutral-200">
                <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0" />
                <span>POSIX flock: kernel cleans locks automatically on SIGKILL or crash</span>
              </div>
              <div className="flex items-start gap-2 text-neutral-200">
                <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0" />
                <span>Direct access to host git, compilers, and toolchains without barriers</span>
              </div>
            </div>
          </div>
        </div>

        {/* Interactive Filesystem Explorer */}
        <div className="p-6 rounded-xl border border-neutral-800 bg-neutral-900/60 mb-16">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-6 pb-4 border-b border-neutral-800">
            <div>
              <h3 className="text-lg font-bold text-white flex items-center gap-2">
                <Folder className="w-4 h-4 text-amber-400" />
                <span>Instance Anatomy Explorer</span>
              </h3>
              <p className="text-xs text-neutral-400 mt-1">
                Click any directory or file below to inspect how <code className="text-neutral-200 font-mono">~/.golunch/instances/work/</code> isolates state.
              </p>
            </div>
            <div className="text-xs font-mono text-neutral-400 bg-neutral-950 px-3 py-1.5 rounded border border-neutral-800 flex items-center gap-2">
              <span className="text-emerald-400">ROOT:</span>
              <span>~/.golunch/instances/work/</span>
            </div>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
            {/* Tree nodes list */}
            <div className="lg:col-span-5 space-y-1.5">
              {INSTANCE_STRUCTURE.map((node) => (
                <button
                  key={node.name}
                  onClick={() => setSelectedNode(node)}
                  className={`w-full text-left px-3 py-2.5 rounded-lg text-xs font-mono flex items-center justify-between transition-all cursor-pointer ${
                    selectedNode.name === node.name
                      ? 'bg-amber-500/15 border border-amber-500/40 text-amber-300'
                      : 'bg-neutral-950/60 border border-neutral-800/80 text-neutral-300 hover:border-neutral-700'
                  }`}
                >
                  <div className="flex items-center gap-2.5 truncate">
                    {node.type === 'folder' ? (
                      <Folder className="w-3.5 h-3.5 text-amber-400 shrink-0" />
                    ) : (
                      <FileCode className="w-3.5 h-3.5 text-cyan-400 shrink-0" />
                    )}
                    <span className="font-semibold">{node.name}</span>
                  </div>
                  <span className="text-[10px] text-neutral-500 truncate max-w-[120px]">
                    {node.type}
                  </span>
                </button>
              ))}
            </div>

            {/* Inspector Details View */}
            <div className="lg:col-span-7 rounded-lg border border-neutral-800 bg-neutral-950 p-4 font-mono text-xs flex flex-col justify-between">
              <div>
                <div className="flex items-center justify-between pb-3 mb-3 border-b border-neutral-800/80">
                  <div className="flex items-center gap-2">
                    <span className="text-amber-400 font-bold">{selectedNode.name}</span>
                    <span className="text-neutral-500 text-[11px]">({selectedNode.type})</span>
                  </div>
                  <span className="text-emerald-400 text-[11px]">BuildEnv Verified</span>
                </div>
                
                <p className="text-neutral-300 text-xs font-sans mb-4 leading-relaxed">
                  {selectedNode.desc}
                </p>

                {selectedNode.content && (
                  <div className="bg-neutral-900/90 rounded p-3 border border-neutral-800 text-neutral-300 overflow-x-auto max-h-56 leading-relaxed whitespace-pre font-mono text-[11px]">
                    {selectedNode.content}
                  </div>
                )}
              </div>

              <div className="mt-4 pt-3 border-t border-neutral-800/60 flex items-center justify-between text-[11px] text-neutral-500 font-sans">
                <span>Kernel descriptor: <code className="text-neutral-400">flock(2)</code> protected</span>
                <span>POSIX compliant</span>
              </div>
            </div>
          </div>
        </div>

        {/* Proxy Precedence Engine */}
        <div className="p-6 rounded-xl border border-neutral-800 bg-neutral-900/40">
          <div className="max-w-2xl mb-6">
            <h3 className="text-lg font-bold text-white flex items-center gap-2">
              <Network className="w-4 h-4 text-cyan-400" />
              <span>The Deterministic Proxy Precedence Engine</span>
            </h3>
            <p className="text-xs text-neutral-400 mt-1">
              golunch deletes all 8 proxy variables and injects matching lowercase and uppercase keys with an enforced loopback floor.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
            {proxyTiers.map((p, idx) => (
              <div
                key={p.tier}
                onClick={() => setActiveProxyTier(idx)}
                className={`p-4 rounded-lg border transition-all cursor-pointer ${
                  activeProxyTier === idx
                    ? 'bg-neutral-900 border-amber-500/50 shadow-md'
                    : 'bg-neutral-950/60 border-neutral-800 hover:border-neutral-700'
                }`}
              >
                <div className="text-[11px] font-mono text-amber-400 mb-1">{p.badge}</div>
                <div className="text-sm font-semibold text-white mb-2">{p.tier}</div>
                <div className="text-xs font-mono text-neutral-400 bg-neutral-950 p-1.5 rounded mb-2 border border-neutral-800 truncate">
                  {p.spec}
                </div>
                <p className="text-xs text-neutral-400 font-sans leading-relaxed">
                  {p.description}
                </p>
              </div>
            ))}
          </div>

          {/* Loopback floor callout */}
          <div className="mt-6 p-3.5 rounded-lg bg-neutral-950 border border-neutral-800 flex items-start gap-3 text-xs text-neutral-300">
            <Lock className="w-4 h-4 text-emerald-400 shrink-0 mt-0.5" />
            <div className="space-y-1">
              <span className="font-semibold text-white">Loopback Floor Guarantee:</span>
              <p className="text-neutral-400 leading-relaxed font-sans">
                <code className="text-neutral-300 font-mono">NO_PROXY</code> and <code className="text-neutral-300 font-mono">no_proxy</code> are always injected with <code className="text-amber-300 font-mono">localhost, 127.0.0.1, 127.0.0.0/8, ::1, .localhost, 169.254.169.254</code> and your machine hostname. An agent talking to a local Ollama server, local MCP daemon, or host database is never accidentally routed into a corporate proxy tunnel.
              </p>
            </div>
          </div>
        </div>

      </div>
    </section>
  );
};
