package instance

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/raaaas/golunch/proxy"
)

// launcherHeader documents provenance inside the generated file so a human
// who finds ~/.local/bin/kilo-work knows where it came from and what to edit.
const launcherHeader = `#!/usr/bin/env bash
# golunch launcher for instance %q
# Generated by golunch -- do not edit by hand. Change metadata.toml and run
# "golunch new --force" (or "golunch refresh") to regenerate this file.
#
# This script is the standalone equivalent of "golunch run %s": both build
# their environment from the same code, so invoking the alias directly and
# invoking it through golunch cannot drift apart.
set -euo pipefail
`

// LauncherPath is where the generated script lives.
func (i *Instance) LauncherPath() string { return filepath.Join(i.Root, "launcher") }

// RenderLauncher produces the bash script body from an already-built Env, so
// the launcher is a projection of BuildEnv rather than a second implementation
// of it. The proxy Resolution is passed alongside because "no proxy variables
// in the Env" is ambiguous — it means either "inherit" or "force off" — and
// guessing wrong would silently un-break the one case the none sentinel exists
// for.
func RenderLauncher(alias string, e *Env, inst *Instance, target []string, res proxy.Resolution) string {
	var b strings.Builder
	fmt.Fprintf(&b, launcherHeader, alias, alias)

	b.WriteString("\n# Isolation: a private HOME, XDG base dirs, tmp and bin/.\n")
	// Only decided values are baked. Host-inherited variables are left to the
	// caller's own environment, so a launcher written today does not freeze
	// last week's PATH into a permanent script.
	isolation := map[string]bool{}
	for _, k := range e.ProxyKeys() {
		isolation[k] = true
	}
	var other []string
	for _, k := range e.Baked() {
		if !isolation[k] {
			other = append(other, k)
		}
	}
	b.WriteString(e.RenderKeys(other))

	if res.Profile.Disabled() {
		// Force-unset, not merely "don't set": a host that exports a proxy must
		// not leak it in through the launcher path, or `golunch run --proxy none`
		// and the launcher would disagree.
		b.WriteString("\n" + LauncherProxyComment("disabled by metadata/proxy spec \"none\"") + "unset")
		for _, pair := range proxy.CaseVars {
			b.WriteString(" " + pair.Upper + " " + pair.Lower)
		}
		b.WriteString("\n")
	} else if pk := e.ProxyKeys(); len(pk) > 0 {
		b.WriteString("\n" + LauncherProxyComment(e.ProxyLayer()))
		b.WriteString(e.RenderKeys(pk))
	} else {
		b.WriteString("\n" + LauncherProxyComment("inherited from the calling shell") + "\n")
	}

	b.WriteString("\n# Storage dirs must exist before exec; agents do not all mkdir -p.\n")
	b.WriteString("mkdir -p")
	for _, d := range storageDirs {
		b.WriteString(" " + ShellQuote(inst.Dir(d)))
	}
	b.WriteString("\n\n")

	if len(target) == 0 {
		target = []string{inst.BinDir() + "/" + alias}
	}
	parts := make([]string, 0, len(target))
	for _, t := range target {
		parts = append(parts, ShellQuote(t))
	}
	b.WriteString("exec " + strings.Join(parts, " ") + " \"$@\"\n")
	return b.String()
}

// WriteLauncher writes the script mode 0755 and links it into binDir so the
// alias becomes an ordinary command. A failed symlink falls back to a copy:
// ~/.local/bin may live on a different filesystem, or be a bind-mounted
// directory that refuses symlinks, and neither should lose the user their
// command.
func WriteLauncher(path, linkPath string, body string) error {
	if err := os.WriteFile(path, []byte(body), 0o755); err != nil {
		return fmt.Errorf("write launcher %s: %w", path, err)
	}
	if linkPath == "" {
		return nil
	}
	if err := os.MkdirAll(filepath.Dir(linkPath), 0o755); err != nil {
		return fmt.Errorf("create %s: %w", filepath.Dir(linkPath), err)
	}
	// Replace any previous target, including a stale copy from an earlier
	// fallback install.
	_ = os.Remove(linkPath)
	if err := os.Symlink(path, linkPath); err == nil {
		return nil
	}
	data, readErr := os.ReadFile(path)
	if readErr != nil {
		return readErr
	}
	if err := os.WriteFile(linkPath, data, 0o755); err != nil {
		return fmt.Errorf("copy launcher to %s: %w", linkPath, err)
	}
	return nil
}

// RemoveLink deletes the ~/.local/bin entry for an instance.
func RemoveLink(linkPath string) error {
	if linkPath == "" {
		return nil
	}
	err := os.Remove(linkPath)
	if os.IsNotExist(err) {
		return nil
	}
	return err
}

// LinkIsOurs guards against deleting an unrelated command that happens to
// share an alias, e.g. a real binary the user installed as "kilo-work".
func LinkIsOurs(linkPath, instLauncher string) bool {
	st, err := os.Lstat(linkPath)
	if err != nil {
		return false
	}
	if st.Mode()&os.ModeSymlink != 0 {
		dest, err := os.Readlink(linkPath)
		return err == nil && filepath.Clean(dest) == filepath.Clean(instLauncher)
	}
	// A copied launcher: compare contents.
	a, err := os.ReadFile(linkPath)
	if err != nil {
		return false
	}
	b, err := os.ReadFile(instLauncher)
	if err != nil {
		return false
	}
	return string(a) == string(b) && strings.Contains(string(a), "# golunch launcher for instance")
}

// LauncherProxyComment is the provenance line embedded above the proxy block.
func LauncherProxyComment(resolved string) string {
	return "# golunch proxy: " + resolved + "\n"
}
